# Generated by Django 6.0.5 on 2026-08-13 09:33

import payrolls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_bank_name'),
        ('payrolls', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payroll',
            name='company_bank_account',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='payroll',
            name='company_bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payroll',
            name='company_gst',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='payroll',
            name='company_reg_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='year',
            field=models.PositiveIntegerField(default=payrolls.models.current_year),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.UniqueConstraint(fields=('employee', 'month', 'year'), name='unique_payroll_period'),
        ),
    ]
