# Generated by Django 6.0.5 on 2026-09-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_invoice_options_invoice_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Khali chhodo toh auto-generate hoga. Direct edit karke custom number bhi daal sakte ho.', max_length=50),
        ),
    ]
