# Generated by Django 6.0.5 on 2026-06-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
