# Generated by Django 6.0.5 on 2026-06-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='report_analytics/'),
        ),
    ]
