# Generated by Django 6.0.5 on 2026-06-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='report_attachment/'),
        ),
    ]
