# Generated by Django 6.0.5 on 2026-08-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_report_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('sick_leave', 'Sick Leave'), ('casual_leave', 'Casual Leave'), ('emergency_leave', 'Emergency Leave'), ('unpaid_leave', 'Unpaid Leave')], max_length=20),
        ),
    ]
