# Generated by Django 6.0.5 on 2026-08-10 11:38

import report.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_alter_report_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='report_attachment/%Y/%m/', validators=[report.models.validate_image_size]),
        ),
    ]
