# Generated by Django 6.0.5 on 2026-06-03 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Punch', '0001_initial'),
        ('attendance', '0001_initial'),
        ('employees', '0002_employee_bio_employee_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='punchsession',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punch_sessions', to='attendance.attendance'),
        ),
        migrations.AddField(
            model_name='punchsession',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_sessions', to='employees.employee'),
        ),
        migrations.AddIndex(
            model_name='punchsession',
            index=models.Index(fields=['employee', 'date'], name='PunchSessio_employe_27b1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='punchsession',
            index=models.Index(fields=['status'], name='PunchSessio_status_5eb87f_idx'),
        ),
    ]
