# Generated by Django 6.0.5 on 2026-06-08 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Punch', '0002_initial'),
        ('attendance', '0002_initial'),
        ('employees', '0002_employee_bio_employee_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punchsession',
            name='attendance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punch_session', to='attendance.attendance'),
        ),
        migrations.AddConstraint(
            model_name='punchsession',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_daily_session'),
        ),
    ]
