# Generated by Django 6.0.5 on 2026-08-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Punch', '0003_alter_punchsession_attendance_and_more'),
        ('attendance', '0002_initial'),
        ('employees', '0003_employee_bank_account'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='punchsession',
            index=models.Index(fields=['punch_in_at'], name='PunchSessio_punch_i_37af21_idx'),
        ),
    ]
